name: Deploy Laravel to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
       # Build Vite assets AFTER Node.js is installed on EC2
        script: |
          cd /var/www/laravel

          # Mark safe directory
          git config --global --add safe.directory /var/www/laravel

          # Pull latest code
          git pull origin main

          # Set proper permissions
          sudo chown -R ubuntu:www-data /var/www/laravel
          sudo chmod -R 775 /var/www/laravel/storage /var/www/laravel/bootstrap/cache
          sudo chmod -R 755 /var/www/laravel

          # Composer & Laravel
          sudo -u www-data composer install --no-dev --optimize-autoloader
          sudo -u www-data php artisan migrate --force
          sudo -u www-data php artisan config:cache
          sudo -u www-data php artisan route:cache
          sudo -u www-data php artisan optimize

          # Build Vite assets (requires Node.js)
          npm install
          npm run build
